/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2014-9-13: 12h:27m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/kiwamu/src/ATS-Postiats/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/home/kiwamu/src/ATS-Postiats/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
/home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 39(line=3, offs=1) -- 92(line=6, offs=3)
*/
ATSextcode_beg()
// #include <avr/io.h>
#include <util/delay.h>
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_int2char0)
ATSdyncst_mac(_delay_ms)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_1() ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

/*
/home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 519(line=20, offs=17) -- 837(line=30, offs=2)
*/
/*
local: 
global: mainats_void_0$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0) ;
ATStmpdec_void(tmp11) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 513(line=20, offs=11) -- 837(line=30, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 524(line=20, offs=22) -- 837(line=30, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 807(line=28, offs=42) -- 815(line=28, offs=50)
*/
ATSINSmove(tmp13, atspre_int2char0(ATSPMVintrep(0xff))) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 777(line=28, offs=12) -- 816(line=28, offs=51)
*/
ATSINSmove_void(tmp11, ATSLIB_056_prelude_056_unsafe__ptr0_set__2__3(ATSextval((0x04 + 0x20)), tmp13)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 828(line=29, offs=12) -- 835(line=29, offs=19)
*/
ATSINSmove_void(tmpret0, loop_1()) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 524(line=20, offs=22) -- 837(line=30, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_void_0] */

/*
/home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 532(line=21, offs=7) -- 765(line=27, offs=4)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_1()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret1) ;
ATStmpdec_void(tmp2) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_char)) ;
ATStmpdec_void(tmp6) ;
ATStmpdec_void(tmp7) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_char)) ;
ATStmpdec_void(tmp10) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 532(line=21, offs=7) -- 765(line=27, offs=4)
*/
ATSINSflab(__patsflab_loop_1):
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 542(line=21, offs=17) -- 765(line=27, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 588(line=22, offs=45) -- 599(line=22, offs=56)
*/
ATSINSmove(tmp5, atspre_int2char0(ATSPMVintrep(0xff))) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 557(line=22, offs=14) -- 600(line=22, offs=57)
*/
ATSINSmove_void(tmp2, ATSLIB_056_prelude_056_unsafe__ptr0_set__2__1(ATSextval((0x05 + 0x20)), tmp5)) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 614(line=23, offs=14) -- 640(line=23, offs=40)
*/
ATSINSmove_void(tmp6, _delay_ms(ATSPMVfloat(500.000000000000000000))) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 686(line=24, offs=45) -- 698(line=24, offs=57)
*/
ATSINSmove(tmp9, atspre_int2char0(ATSPMVintrep(0x00))) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 655(line=24, offs=14) -- 699(line=24, offs=58)
*/
ATSINSmove_void(tmp7, ATSLIB_056_prelude_056_unsafe__ptr0_set__2__2(ATSextval((0x05 + 0x20)), tmp9)) ;

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 713(line=25, offs=14) -- 739(line=25, offs=40)
*/
ATSINSmove_void(tmp10, _delay_ms(ATSPMVfloat(500.000000000000000000))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 754(line=26, offs=14) -- 761(line=26, offs=21)
*/
ATStailcal_beg()
ATSINSfgoto(__patsflab_loop_1) ;
ATStailcal_end()

/*
emit_instr: loc0 = /home/kiwamu/src/arduino-mega2560-ats/demo/blink_ats/DATS/main.dats: 542(line=21, offs=17) -- 765(line=27, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [loop_1] */

#if(0)
/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2077(line=75, offs=3) -- 2300(line=83, offs=2)
*/
/*
local: 
global: ptr0_set$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5070)
tmparg = S2Evar(a(5070))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2066(line=74, offs=1) -- 2300(line=83, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a)), arg1) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSmove_void(tmpret3, ATSempty()) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__2] */
#endif // end of [TEMPLATE]

/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2077(line=75, offs=3) -- 2300(line=83, offs=2)
*/
/*
local: 
global: ptr0_set$2$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5070)
tmparg = S2Evar(a(5070))
tmpsub = Some(a(5070) -> S2Ecst(char_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_char) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2066(line=74, offs=1) -- 2300(line=83, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char)), arg1) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSmove_void(tmpret3__1, ATSempty()) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__2__1] */

/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2077(line=75, offs=3) -- 2300(line=83, offs=2)
*/
/*
local: 
global: ptr0_set$2$2(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5070)
tmparg = S2Evar(a(5070))
tmpsub = Some(a(5070) -> S2Ecst(char_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_char) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3__2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2066(line=74, offs=1) -- 2300(line=83, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char)), arg1) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSmove_void(tmpret3__2, ATSempty()) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3__2) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__2__2] */

/*
/home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2077(line=75, offs=3) -- 2300(line=83, offs=2)
*/
/*
local: 
global: ptr0_set$2$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5070)
tmparg = S2Evar(a(5070))
tmpsub = Some(a(5070) -> S2Ecst(char_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__2__3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_char) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3__3) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2066(line=74, offs=1) -- 2300(line=83, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char)), arg1) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2269(line=81, offs=12) -- 2276(line=81, offs=19)
*/
ATSINSmove_void(tmpret3__3, ATSempty()) ;
/*
emit_instr: loc0 = /home/kiwamu/src/ATS-Postiats/prelude/DATS/unsafe.dats: 2086(line=75, offs=12) -- 2300(line=83, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3__3) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__2__3] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_kiwamu_057_src_057_arduino_055_mega2560_055_ats_057_demo_057_blink_ats_057_DATS_057_main_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
